# Generated by Django 4.1.7 on 2023-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_voter',
            field=models.BooleanField(default=True),
        ),
    ]
