# Generated by Django 4.1.7 on 2023-02-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_voter',
            field=models.BooleanField(default=False),
        ),
    ]
