# Generated by Django 4.1.7 on 2023-02-17 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_uid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
