# Generated by Django 4.1.7 on 2023-02-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_election_election_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cand_name', models.CharField(max_length=150, verbose_name='Candidate Name')),
                ('cand_email', models.EmailField(max_length=254, unique=True, verbose_name='Candidate Email')),
                ('cand_state', models.CharField(choices=[('', 'Select...'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100, verbose_name='Candidate State')),
                ('cand_const', models.CharField(max_length=200, verbose_name='Candidate Constituency')),
                ('cand_party', models.CharField(max_length=150, verbose_name='Party Name')),
                ('cand_about', models.TextField(verbose_name='About')),
                ('total_votes', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('cand_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cand_election', to='core.election')),
            ],
        ),
    ]
