# Generated by Django 4.1.7 on 2023-02-17 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_uid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
