# Generated by Django 4.1.7 on 2023-02-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cand_const',
            field=models.CharField(choices=[('', 'Select...')], max_length=200, verbose_name='Candidate Constituency'),
        ),
        migrations.AlterField(
            model_name='election',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
