# Generated by Django 4.1.7 on 2023-02-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_candidate_cand_const_alter_election_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cand_const',
            field=models.CharField(max_length=200, verbose_name='Candidate Constituency'),
        ),
    ]
